version: '3'

volumes:
  pg_data:
  static_volume:

services:
  db:
    image: postgres:13.10-alpine
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
  frontend:
    image: kfifa3956/alfa:latest
    env_file: .env
    volumes:
      - ./frontend/:/app/result_build/
      - ./.env:/app/result_build/dist/.env
  backend:
    image: artemiiru/alfabank_hackathon:latest
    env_file: .env
    ports:
      - "8000:8000"
    volumes:
      - static_volume:/backend_static
      - ./.env:/app
    depends_on:
      - db
  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - ./conf.d:/etc/nginx/conf.d/default.conf
      - ./media:/usr/share/nginx/html/media
      - static_volume:/static
      - ./frontend/dist:/usr/share/nginx/html
    depends_on:
      - backend
      - frontend
